FROM python:3.13-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy exporter code
COPY docker_api_exporter.py .

# Run exporter
CMD ["python", "docker_api_exporter.py"]