receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

exporters:
  debug:
    verbosity: detailed

  otlp/tempo:
    endpoint: tempo:9095
    tls:
      insecure: true

service:
  telemetry:
    logs:
      level: warn # Only warn, error, fatal
      encoding: json
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, debug]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
