global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api"
    static_configs:
      - targets: ["api:8000"] # port where OTEL Prometheus exporter is exposed
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-exporter:9113"] # Exporter URL
  - job_name: "docker_services_health"
    static_configs:
      - targets: ["docker-api-exporter:9100"]

rule_files:
  - "alerts/prometheus-service-alerts.yaml"
