# tempo.yaml for Tempo v2.9.0

server:
  http_listen_port: 3200 # HTTP query frontend
  log_level: warn # Only warn, error, fatal
  log_format: json

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  max_block_duration: 5m

metrics_generator:
  storage:
    path: /tempo-data/generator

storage:
  trace:
    backend: local
    local:
      path: /tempo-data/blocks
    wal:
      path: /tempo-data/wal
